spring:
  application:
    name: tlias-web-management
  # 配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xzb0603

# mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射开关，可以映射数据库字段为Java属性（原先mysql中用下划线命名的值就会变成驼峰命名）
    map-underscore-to-camel-case: true